### ISSUE TITLE
[Android] Where should i put the rtp into?

### ISSUE THREAD

**Issue by Yabuato** [libretro/easyrpg-libretro#16]
Where am I supposed to place the RTP files in order for RPG Maker 2000 games to work? I've tried dropping the RTP folder into the system folder where all the bios files are located, but that doesn't work.

**Comment by Ghabry** [comment]
RTP is currently not supported by the libretro core

**Comment by Yabuato** [comment]
Hey,you're the official dev right?Thanks for maintaining libretro port!

**Comment by Ghabry** [comment]
Yes, I'm one of the official devs and maintaining it since a few weeks, at least the code is not out-of-sync anymore.

I want to fix the stuff that isn't broken in our official app, like Windows support, button mappings, RTP, MP3 playback and non-English games (that should be all...).

No plans for libretro specific features because I'm not using RetroArch at all ^^'

**Comment by Yabuato** [comment]
Those broken features in libretro android port you're going to fix is enough to make it become a good port,thanks you so much for taking time for this!

**Comment by Ghabry** [comment]
because this is RetroArch/libretro API stuff will need the help of somebody who knows how RetroArch works for this.
There should be a generic solution for all platforms, where are assets usually put?

**Comment by Ghabry** [comment]
I set the path to SYTEM_DIRECTORY/rtp/2000 and SYSTEM_DIRECTORY/rtp/2003 which is documented as:
```cpp
#define RETRO_ENVIRONMENT_GET_SYSTEM_DIRECTORY 9
                                           /* const char ** --
                                            * Returns the "system" directory of the frontend.
                                            * This directory can be used to store system specific 
                                            * content such as BIOSes, configuration data, etc.
                                            * The returned value can be NULL.
                                            * If so, no such directory is defined,
                                            * and it's up to the implementation to find a suitable directory.
                                            *
                                            * NOTE: Some cores used this folder also for "save" data such as 
                                            * memory cards, etc, for lack of a better place to put it.
                                            * This is now discouraged, and if possible, cores should try to 
                                            * use the new GET_SAVE_DIRECTORY.
                                            */
```

**Comment by Yabuato** [comment]
Sorry for the super late reply,I just wanna thank you,I almost forget this issue.I'm going to test it!

**Comment by Ghabry** [comment]
GET_SYSTEM_DIRECTORY seems to return the game directory.

by now it supports two directories btw, the second is the media directory where the media downloader puts the files (retroarch/downloads but I guess this folder also depends on the platform)
