### ISSUE TITLE
Bugs with wav sounds and also with accents

### ISSUE THREAD

**Issue by spielvan** [libretro/easyrpg-libretro#17]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Name of the game:

Rygar e os soldados do rei

#### Player platform:
Windows, Linux, Android, ...

Android 4.4.2

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

#### Describe the issue in detail and how to reproduce it:

Hello personal version of the easy rpg for the retroarch android is very good, congratulations only have two bugs, which do not occur with the easy rpg version separated:

1. The wav sound gives error and does not load, showing an error message in the upper part of the screen, leaving the games without sound (in the separate version of Easy rpg they run perfectly).

2 The part of the dialogues of text in the game, with the game translated into Portuguese, the accentuation part is bugada and also the words lose letters like  " você esta bem, Fica vocstem" 

A hug and success always

**Comment by Ghabry** [comment]
The retro "port" currently lacks support for most WAV files and has no MP3 support and there is also no way to configure the game encoding (and autodetection doesn't work because the ICU library is missing)

The easyrpg port was just updated to the latest version today, fixing the audio is the next step.

You can fix the encoding problem for now by doing the following:
Open the RPG_RT.ini of the game with a text editor and add:
```
[EasyRPG]
Encoding=1252
```

**Comment by spielvan** [comment]
Thank you, revolved the problem of subtitles, now only wait for a future update solving the problem in the sound, too much is running perfect, also for the great work.

**Comment by ghotinggoad** [comment]
Hi, I would love to see the latest commit to the core so I can use my gamepad with EasyRPG on my android phone.

**Comment by Ghabry** [comment]
About which latest commit are you talking? I never changed any gamepad code.

**Comment by ghotinggoad** [comment]
What I meant is that I would like to see the audio being fixed so I can make use of libretro's input libraries. Sorry for the confusion.

**Comment by Ghabry** [comment]
This is now solved. Please wait up to 24 hours for the core to recompile on the buildbot.
The new version will not work on all platforms yet, I create a new issue to track the platform progress.

**Comment by spielvan** [comment]
> This is now solved. Please wait up to 24 hours for the core to recompile on the buildbot.
> The new version will not work on all platforms yet, I create a new issue to track the platform progress.

So this new version of easyrpg-libretro pro android, will recognize the wav audios? a hug.

**Comment by Ghabry** [comment]
sorry, Android is not supported yet. Getting this to compile needs extra work because building for Android is no fun at all.
Will get the Windows build working first...

**Comment by Ghabry** [comment]
I track the platform progress here: https://github.com/libretro/easyrpg-libretro/issues/25
When it has a tick it will work.

**Comment by spielvan** [comment]
> I track the platform progress here: #25
> When it has a tick it will work.

Thank you so much my dear.

**Comment by ghotinggoad** [comment]
Thank you so much sir!
