### ISSUE TITLE
Missing letters (ö, ä, ü, Ö, Ä, Ü, ß)

### ISSUE THREAD

**Issue by Kupo91** [libretro/easyrpg-libretro#18]
**Update:** 
I dont know why but ingame speed is correct now even if nothing of my setup has changed I guess.
So just the issue with the letters remains. I wrote down the words where letters are missing. And it always seems to be words with the german letters ö, ä, ü, Ö, Ä, Ü, ß. However sometimes there are also missing 2 further letters. I give you some examples from the first scenes of Vampires Dawn.
Missing letters are written **big**:

**ü**berspringen
erz**ähl**e
B**Ö**SE
f**ü**rchte
m**ö**chtest
**ü**ber
f**ü**r
Gew**äss**er
**ü**berqueren
k**ö**nnen
dar**ü**ber
aufgez**ähl**t
h**ö**r
schw**äch**er
Sch**ö**pfer
sp**äte**re
t**ö**ten
l**ähm**en
schl**ägs**t
f**ü**llst
flie**ß**t

So as you can see its always one of the letters I mentioned in the beginning and sometimes its also the two next letters.

--------------------------------------------

Hi, after the aspect ratio is fixed I gave this core another try. However I'm still struggling with 2 issues.

Name of the game: Vampires Dawn

Player platform: Linux (I run LibreElec 8.2.3.1 with Retroarch 7.0.2-j08 with an ARM S905X chip)

Describe the issue in detail and how to reproduce it: 
Issue 1: The ingame speed is like 800%. It's hard to go through a door because he runs so fast.
Issue 2: The font. Some letters are missing.

**Comment by Kupo91** [comment]
Update

**Comment by Ghabry** [comment]
Thats because of missing language autodetect in the libretro version.

Edit the RPG_RT.ini with a text editor and put

```
[EasyRPG]
Encoding=1252
```
at the end

**Comment by Kupo91** [comment]
That works :))) Thank you so much

**Comment by Ghabry** [comment]
This is now solved. Please wait up to 24 hours for the core to recompile on the buildbot.
The new version will not work on all platforms yet, I create a new issue to track the platform progress.
