### ISSUE TITLE
Closing core crashs Retroarch

### ISSUE THREAD

**Issue by Kupo91** [libretro/easyrpg-libretro#19]
Name of the games: Vampires Dawn - Reign of Blood and Vampires Dawn II - Ancient Blood

Player platform: Linux (I run LibreElec 8.2.3.1 with Retroarch 7.0.2-j08 with an ARM S905X chip)

Describe the issue in detail and how to reproduce it: Well I tested it on 2 platforms. 
On the one hand I run LibreElec 8.2.3.1 and Retroarch is integrated as addon. So usually I run Retroarch from my addon menu in Kodi and if I close Retroarch I end up in Kodi again. So if I close an emu core in Retroarch I usually end up in Retroarch main menu first and then I can quit Retroarch to go back to Kodi again. But in easyrpg's case I don't end up in Retroarch but in Kodi.
On the other hand I recently tested Lakka 2.1 on my sd card. And there is no Kodi where i could end up after closing easyrpg so I end up in Retroarch main menu. But closing easyrpg still looks a bit different than closing other cores. Not so smooth. So I still think there is something wrong.

**Comment by Ghabry** [comment]
should be resolved in the next build in ~24 h

**Comment by Kupo91** [comment]
I confirm it doesn't crash anymore. And it seems to have some nice side effects aswell. In the past everytime I pressed Select+Start on my controller (those are the hotkeys for retroarch menu) the msg box continued because of the start button. But now it doesn't happen anymore. 
Furthermore the screenshot issue https://github.com/libretro/easyrpg-libretro/issues/23 seems to be fixed now too.

**Comment by Ghabry** [comment]
> I confirm it doesn't crash anymore. And it seems to have some nice side effects aswell. In the past everytime I pressed Select+Start on my controller (those are the hotkeys for retroarch menu) the msg box continued because of the start button. But now it doesn't happen anymore.


hm, I didn't fix this but good to have this resolved :D
