### ISSUE TITLE
Problems with Windows buildbots

### ISSUE THREAD

**Issue by ofry** [libretro/easyrpg-libretro#2]
#### Describe the issue in detail and how to reproduce it:

This core doesn't present in Windows x86-64 buildbot.

https://buildbot.libretro.com/nightly/windows/x86_64/latest/

**Comment by Ghabry** [comment]
good news, I hope to resolve it this month ;)

**Comment by Ghabry** [comment]
compiles on my Windows system ... closing for now, please wait a day before checking again, the buildbots are slooooooooooooooow

**Comment by Ghabry** [comment]
reopening, have unknown issues on the buildbot :/

**Comment by Ghabry** [comment]
Added a static makefile workaround because the libretro Windows buildbot is broken and doesn't work correctly with CMake... This should work until we move stuff around in upstream repo.

**Comment by Ghabry** [comment]
The resulting file was corrupted (an exe instead of dll), the core actually works now ;)
