### ISSUE TITLE
A & B button is swapped

### ISSUE THREAD

**Issue by Kupo91** [libretro/easyrpg-libretro#20]
Name of the games: Vampires Dawn - Reign of Blood and Vampires Dawn II - Ancient Blood

Player platform: Linux (I run LibreElec 8.2.3.1 with Retroarch 7.0.2-j08 with an ARM S905X chip), Lakka 2.1

Describe the issue in detail and how to reproduce it: Actually button A is OK and button B is Cancel but in easyrpg it is swapped. Furthermore according to [https://docs.libretro.com/library/easyrpg/#features](https://docs.libretro.com/library/easyrpg/#features) there should be an controls option which doesn't exist atm.

Edit: Okay in Lakka 2.1 the controls option exist but I can't change the buttons.

**Comment by Kupo91** [comment]
I just noticed that it is the same with the Gameboy cores in Retroarch. So even if you can't change controls in Retroarch menu or there isn't even such a menu you are still able to create a remap file for easyrpg and put it to the others. So everything is fine now :)

**Comment by Ghabry** [comment]
no idea, will need the help of somebody who knows how RetroArch works

**Comment by Ghabry** [comment]
This will be solved as part of https://github.com/EasyRPG/Player/pull/1464

Adds support for the whole keyboard (as you would expect from native EasyRPG Player) and RetroPad remapping.
