### ISSUE TITLE
Screenshot issue

### ISSUE THREAD

**Issue by Kupo91** [libretro/easyrpg-libretro#23]
#### Describe the issue in detail and how to reproduce it:
If you go into the core menu and take a screenshot everyhting is fine. However if you take a screenshot by pressing a hotkey instead the screenshots are broken.

Normal (by core menu):
![rpg_rt-181105-023920](https://user-images.githubusercontent.com/41426906/47975140-fd17eb00-e0ac-11e8-8013-a3bc5213fb5d.png)

By hotkey:
![rpg_rt-181105-023049](https://user-images.githubusercontent.com/41426906/47975162-099c4380-e0ad-11e8-924a-ec668b016267.png)
![rpg_rt-181105-023014](https://user-images.githubusercontent.com/41426906/47975163-0c973400-e0ad-11e8-9e36-c9d52004a11c.png)

**Comment by Ghabry** [comment]
no idea, will need the help of somebody who knows how RetroArch works

**Comment by Kupo91** [comment]
Maybe I should add that I don't use the latest version of RetroArch but one from last year. I also tried it with the latest version but I cant find my screenshots there. Maybe because the newer version is only on SD card while the older one is written to internal (included in Kodi). And many directory paths lead to a temp folder which is empty if I open it. Even if I change the screenshot path to my USB stick there are still no screenshots. So I cant say for sure that it looks the same in newer versions of RetroArch..

**Comment by Ghabry** [comment]
no problem, please keep us updated.

**Comment by Ghabry** [comment]
as mentioned in #19 closing this for now as resolved.
Pls report when the issue reappers, thx.

**Comment by Ghabry** [comment]
Achja, ich persönlich finde ja, Vampires Dawn ist extrem schlecht gealtert, spiel besser Unterwegs in Düsterburg ;)

**Comment by Kupo91** [comment]
Ah, ein Deutscher xD Hab ich auch schon von anderen gelesen, aber was ist denn mit "schlecht gealtert" gemeint? Unterwegs in Düsterburg sagt mir auch noch was, hab ich aber nie richtig gespielt. Bald kommt Vampires Dawn 3. Zu schade, dass das nicht mit EasyRPG läuft

**Comment by Ghabry** [comment]
Naja sobald man die Oberwelt erreicht, also das Spiel "Open World" wird. Weiß gar nicht mehr ab wann das war. Glaub wenn die 3er-Gang vereint ist.
Da läuft man ziemlich ziellos auf der herum und bist stundenlang am grinden, weil die Gegner teilweise zu stark sind ;). Random encounter sind einfach out, selbst die Japaner haben das mittlerweile eingesehen. VD2 soll aber noch immer ganz passabel sein.
Und das Storytelling von UiD ist einfach viel besser, weniger Leerlauf.

**Comment by Kupo91** [comment]
Ja, da ist schon was dran. Man weiß nicht in welchem Gebiet welche Gegner lauern, da kann man auch böse Überraschungen erleben. Nur wenn man schon weiß, wo man hin muss kann man sich das Gegrinde weitgehend sparen. Ich glaube diese Zufallskämpfe stören jeden, vorallem wenn man sie alle 3 Schritte hat.
Das ist bei VD2 nicht mehr der Fall. 
Ich werd bei Gelegenheit mal in UiD reingucken
