### ISSUE TITLE
Platform support

### ISSUE THREAD

**Issue by Ghabry** [libretro/easyrpg-libretro#25]
Status of the new build system:

- [x] Windows 32bit
- [x] Windows 64bit (mingw crossbuild)
- [x] Linux (amd64)
- [x] Linux (other architectures, via libreelec etc.)
- [x] Android armeabi-v7a
- [x] Android arm64-v8a
- [x] Android x86
- [x] Android x86_64
- [x] OSX x86_64
- [x] OSX arm64 
- [ ] iOS
- [x] Vita
- [x] Switch
- [ ] Wii
- [ ] WiiU

**Comment by xTMODx** [comment]
I am waiting for the Android build :) it should have some some benefits over the standalone like sorted playlist

**Comment by Ghabry** [comment]
@xTMODx 
Android port is done, lets wait for the slow buildbot... can only take hours -_-

**Comment by spielvan** [comment]
Got it right, the bug in the audio wav hand?

**Comment by Ghabry** [comment]
> Got it right, the bug in the audio wav hand?

Could you reword this? I don't understand the question.

**Comment by spielvan** [comment]
> > Got it right, the bug in the audio wav hand?
> 
> Could you reword this? I don't understand the question.

The bug that occurred in the android version of easyrpg in retroarch, that it did not detect the audio wav of the game, there the game runs normal, but without the audio.

**Comment by Ghabry** [comment]
this should work now, unfortunately I have the usual "builds locally but not on the buildbot"-situation :/

**Comment by spielvan** [comment]
> this should work now, unfortunately I have the usual "builds locally but not on the buildbot"-situation :/

Is this separate version yours too? https://play.google.com/store/apps/details?id=org.easyrpg.player&hl=pt-BR

I installed and used it, it behaves very good, the sound stays perteito and the accents ... so some games the gamepad does not work, I'll give a tip, nowadays a lot of people play with gamepad, outside the cell phones, would interesting a mobil touch version and another 100% to use with game pad, without touch, congratulations my dear, is a great project and would not be possible a version for playstation 2.

**Comment by Ghabry** [comment]
Yes, that's the official version of EasyRPG Player.

Playstation 2 is impossible, the compiler is too old.

**Comment by Ghabry** [comment]
Android build for arm64 and x86 should work now. Just waiting for the awful, slow buildbot

**Comment by crunchyegg-gg** [comment]
Hi, I'm currently attempting to list every platform and architecture RPG Maker 2K(3) games are playable on.

I have a specific section for the easyrpg-libretro core. Can someone please let me know if I missed anything or anything is inaccurate? Documentation on what exactly specific cores run on seems to be scarce, something I'd like to be able to solve (at least for this specific core). For example, I noticed that macOS's libretro 1.9.0 build seems to include EasyRPG support but here the port is listed as incomplete. I also couldn't verify if EasyRPG is also supported in the version that uses the Metal Renderer as I can't seem to mount Apple's new proprietary filesystem. [EasyRPG's own website](https://easyrpg.org/player/downloads/#release-libretro) claims that the libretro core supports ARM-based GNU/Linux systems but [this post](https://github.com/libretro/easyrpg-libretro/issues/25#issue-382437338) contradicts that. Clarification and a possible update to the first post in this thread would be greatly appreciated.

If anyone has knowledge of what builds are available for what platforms, please take a look at this: https://github.com/crunchyegg-gg/awesome-rm2k3/blob/main/RM2K3-RUNTIME-PORTS.md

Thanks!

**Comment by Ghabry** [comment]
It is listed as incomplete because this is for the new continuous integration system. There are no agents yet for macOS.
But when the macOS bot is up you can assume that the Player will be compiled with it.

So currently the list is as stated above:

- Windows
- Linux (x86 only)
- Android
- Vita
- Switch

But the core itself builds without issues on other Linux versions and on Wii or WIiU - there are just no automatic builds. (you can assume that the core is as portable as the standalone)

The Pandora release is wrong, the version there is 0.6.2.2

-----

If you are also interested in non-open source tools for RPG Maker 2003:
- TKoolBridge
- TKcode Scripter
(can't find the links, japanese tools) they allow writing event script in a text editor and copying them into the RPG Maker editor.

A list of patches for RPG Maker 2003 (not for EasyRPG):
https://rpgmaker.net/forums/topics/689/?p=1

Also "Maniac Patch" - This adds new features to the RPG Maker 2003 engine such as keyboard and mouse input (also not supported by easyrpg yet)

**Comment by Ghabry** [comment]
closing this. if you want a new platform simply open a new issue
