### ISSUE TITLE
Windows: Load content not working when using command line arguments

### ISSUE THREAD

**Issue by whocares0101** [libretro/easyrpg-libretro#34]
#### Name of the game:
VampiresDawn2

#### Player platform:
Windows 7 x64

#### Attach files (as a .zip archive or link them)
 no save, doesn't start
 easyrpg_log.txt is not being created

#### Describe the issue in detail and how to reproduce it:
I tried to run the game from the command line
retroarch.exe --libretro cores\easyrpg_libretro.dll <RPG_RT.ini>
which did not work.

So I tried to add --verbose which prints a few lines but doesn't work either.

Next I tried to run it through the GUI which works but only if there are no command line arguments.
Running "retroarch.exe --verbose" does not work, the window just closes.
It's not just --verbose but "--config retroarch.cfg" yields the same result.

run "retroarch.exe --verbose"
Load core
Load content

Running without any arguments will work and shows the title screen.

[__log_verbose.txt](https://github.com/libretro/easyrpg-libretro/files/2674295/__log_verbose.txt)

**Comment by Ghabry** [comment]
That problem is Windows exclusive, I investigated this 2 weeks ago but couldn't figure it out.

**Comment by whocares0101** [comment]
Now that I finally got this to compile I added a few `Output::DebugStr` to see how far the code executes and this is what I found
```
libretro_wrapper.cpp
// argc and argv == 0
106: Player::Init(0, 0);

player.cpp
// called with argc and argv == 0
160: ParseCommandLine(argc, argv);

// this gets the command line but it will also update argc, being a pointer after all
// after this argc is 2 when running with --verbose
391: LPWSTR *argv_w = CommandLineToArgvW(GetCommandLineW(), &argc);

// argc being 2 will trigger this loop
420: for (int i = 1; i < argc; ++i) {

// and this accesses argv which is still NULL and bang dead
421: ss << argv[i] << " ";
```

Commenting `ParseCommandLine(argc, argv);` does indeed allow the title screen to load even with `--verbose`.
Running as libretro core you shouldn't propably parse the command line to begin with.
The easiest fix is to check `argv` right before the loop `if (!argv) return;`.

**Comment by Ghabry** [comment]
Great, thanks for the help. I will also fix this in the upstream code.

**Comment by Ghabry** [comment]
okay added a patch. Player::Init already resolved 0,0 for argv and argc but the Windows code simply ignores it to get a Unicode command line and then crashes :/.
