### ISSUE TITLE
Update to 0.6

### ISSUE THREAD

**Issue by Ghabry** [libretro/easyrpg-libretro#37]
-

**Comment by Kupo91** [comment]
@Ghabry  Hi, wann wird denn das Update kommen? :)

**Comment by Ghabry** [comment]
Irgendwann im April.
Möchte zuvor endlich mal das upstreamen vom libretro-Code abschließen, da dies das Aktuell halten deutlich vereinfachen würde.

**Comment by Kupo91** [comment]
Keine Ahnung was das bedeutet :D

**Comment by Ghabry** [comment]
Upstreamen: Den libretro spezifischen Code in das Haupt Quellcode repository von EasyRPG Player überführen (bin ja einer der EasyRPG Entwickler). Damit ich nicht immer die Änderungen wenn eine neue Version herauskommt manuell mit den libretro Änderungen zusammen führen muss, was nervig ist.

**Comment by Kupo91** [comment]
Achso okay :) noch was: bei latest commit steht "Use ldb instead of ini"
Also heißt das jetzt, dass man mit dem Emu die ldb Datei statt der ini Datei öffnen soll oder ist damit was anderes gemeint? Weil zur Zeit geht beides. Und in den libretro Docs steht nur was von der ini Datei http://docs.libretro.com/library/easyrpg/#extensions

**Comment by Ghabry** [comment]
Die Docs sind nicht mein Problem.

Es geht beides, weil der Ordner das relevante ist, nicht die Datei. LDB macht nur mehr Sinn als INI weil manche Spiele keine INI haben.

Da man bei libretro mal wieder zu sehr auf Roms fixiert war, kann man leider keine Ordner "starten", nur Dateien...

**Comment by Ghabry** [comment]
Done, waiting for rebuild on all platforms.

Because the code diverged already alot from 0.6 I updated to the latest nightly instead.
Not ideal because of potential regressions in nightlies, will do nightly updates until we reach 0.6.1

**Comment by Ghabry** [comment]
libretro port related changes since last release:

- Audio sample rate changed from 44100 to 48000 (gives a better looking number when doing samplerate / 60)
- The keyboard is now passed through, which means you have the same buttons on the keyboard mapped as in normal EasyRPG Player. Stuff that is already provided by RetroArch (Reset, Fast Forward, Screenshot, FPS) was unmapped, also these buttons conflicted with the huge amount of hotkeys. Because the keyboard can conflict with RetroPad this can be configured in the core options
- RetroPad also maps now Shift and Reset. Because RPG Maker games can use more buttons than RetroPad buttons, you can remap X, R, L (1-3) via the core options.
- Debug / TestPlay mode can be toggled via the core options, the buttons to use this can be mapped via the RetroPad core options (or keyboard: Hold CTRL to disable encounters & walk through walls / Press F10 for the debug menu). Note that some games have anti-cheat functionality which will trigger a game over when you walk on impassable tiles ^^'
- Wildmidi and the RTP (rtp/2000 and rtp/2003) are now also searched in the asset directory, for Wildmidi MIDI playback you can download the instruments through the Content downloader.

I hope the core option stuff works for you because I was unable to figure out how to save them with RetroArch... (at least on Linux, on Windows it works o.O)

**Comment by Ghabry** [comment]
Looks good to me. Enjoy.
