### ISSUE TITLE
No buttons mapped except A & B

### ISSUE THREAD

**Issue by Sandman53** [libretro/easyrpg-libretro#38]
Name of the game: Ara Fell

Player platform: Windows

Describe the issue in detail and how to reproduce it:
The shift button doesn't seemed to be mapped to anything when using RetroArch. When running EasyRPG on it's own the shift button works fine and I can crouch like normal in Ara Fell, however no key combination or gamepad buttons work when using it through RetroArch

**Comment by Ghabry** [comment]
I will directly use this issue as a catch all because there is also no way to map numbers.

**Comment by Ghabry** [comment]
Has now a patch in https://github.com/EasyRPG/Player/pull/1464
Will close this when the PR is merged.
