### ISSUE TITLE
Fail to Launch on Windows 10 due to xAudio2

### ISSUE THREAD

**Issue by zach-morris** [libretro/easyrpg-libretro#39]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Name of the game:
Any game reproduces this issue

#### Player platform:
Windows 10

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)
Verbose log shows:
```
[INFO] XAudio2: Requesting 64 ms latency, using 64 ms latency. 
[ERROR] Failed to init XAudio2.
```
#### Describe the issue in detail and how to reproduce it:
Unable to launch any game using Retroarch 1.7.6 and the latest core available in the buildbot if the Audio driver is set to xaudio2 (which i believe is the default?).  Note that I do have xaudio2 installed (directx) and other cores work with this audio driver set.  If I change the audio driver to something else, like sdl2, then the game launches.

**Comment by Ghabry** [comment]
@zach-morris  I just tested it on Windows 10 and it works for me with Xaudio2:

```
[INFO] XAudio2: Requesting 64 ms latency, using 64 ms latency.
[INFO] [autoconf]: selected configuration: D:\RetroArch\autoconfig\xinput\XInput_Controller_User_1.cfg
[INFO] [Menu]: Found menu display driver: "gl".
```

**Comment by Ghabry** [comment]
no feedback and works for me -> closing

**Comment by zach-morris** [comment]
Just providing more info if you want to investigate further.  I did some more investigation and found it seems to be only when I load from the command line, rather than the Retroarch GUI.

Here's a log when I loaded the game from Retroarch GUI (success):
```
C:\WINDOWS\system32>"C:\Program Files\Retroarch\retroarch_debug.exe" --verbose
...
[INFO] [Video]: Found display server: win32
[INFO] [XAudio2]: Requesting 64 ms latency, using 64 ms latency.
...
[INFO] Using content: D:\Games\ROMS\EasyRPG\8 Bit Quest v1.0.2\RPG_RT.ldb.
[INFO] arg #0: retroarch
[INFO] arg #1: D:\Games\ROMS\EasyRPG\8 Bit Quest v1.0.2\RPG_RT.ldb
[INFO] arg #2: -s
[INFO] arg #3: C:\Program Files\Retroarch\saves
[INFO] arg #4: -S
[INFO] arg #5: C:\Program Files\Retroarch\states
[INFO] arg #6: -c
[INFO] arg #7: C:\Program Files\Retroarch\retroarch.cfg
[INFO] arg #8: -L
[INFO] arg #9: C:\Program Files\Retroarch\cores\easyrpg_libretro.dll
[INFO] Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] Unloading game..
[INFO] Unloading core..
[INFO] Unloading core symbols..
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
[INFO] Set config file to : C:\Program Files\Retroarch\retroarch.cfg
[INFO] RetroArch 1.7.7 (Git 52dd39f98a)
...
[INFO] CRC32: 0x576a4c87 .
[INFO] Environ SET_PIXEL_FORMAT: XRGB8888.
Debug: EasyRPG Player 0.6.0 started
Debug: ============================
Debug: Seeded the RNG with 1558227962.
Debug: CLI:
[INFO] Environ SET_INPUT_DESCRIPTORS:
[libretro INFO] parent dir is: D:\Games\ROMS\EasyRPG\8 Bit Quest v1.0.2
[INFO] Skipping SRAM load..
[INFO] [RCHEEVOS]: Load task finished
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 47952.05 Hz.
[INFO] [Video]: Video @ fullscreen
```

Here's a log when I loaded the same game from the command line (fail):
```
C:\WINDOWS\system32>"C:\Program Files\Retroarch\retroarch_debug.exe"  -L "C:\Program Files\Retroarch\cores\easyrpg_libretro.dll" "D:\Games\ROMS\EasyRPG\8 Bit Quest v1.0.2\RPG_RT.ldb" --verbose
...
[INFO] [Video]: Found display server: win32
[INFO] [Audio]: Starting threaded audio driver ...
[INFO] [Audio Thread]: Initializing audio driver.
[INFO] [XAudio2]: Requesting 64 ms latency, using 64 ms latency.
[ERROR] Failed to init XAudio2.
[ERROR] Cannot open threaded audio driver ... Exiting ...
[ERROR] Fatal error received in: "audio_driver_init_internal()"
[INFO] [Autoconf]: selected configuration: C:\Program Files\Retroarch\autoconfig\xinput\XInput_Controller_User_1.cfg
```

**Comment by Ghabry** [comment]
thanks I filled a bug against RetroArch as cores are not responsible for audio init
