### ISSUE TITLE
Sound is not output when the sound driver is set to wasapi.

### ISSUE THREAD

**Issue by nanitaro** [libretro/easyrpg-libretro#41]
Thank you for supporting the libretro core for EasyRPG Player.

---
Please fill in the following fields before submitting an issue:

#### Name of the game:
Ib 1.07

#### Player platform:
Windows10 64bit Build 1809

#### Attach files (as a .zip archive or link them)
[retroarch.log](https://github.com/libretro/easyrpg-libretro/files/3173755/retroarch.log)

[ERROR] [WASAPI]: CoCreateInstance failed with error 0x800401F0.
[ERROR] [WASAPI]: Failed to initialize device.
[ERROR] Cannot open threaded audio driver ... Exiting ...

#### Describe the issue in detail and how to reproduce it:
When the audio driver is Wasapi, no sound is output.
The log contains messages that failed to initialize the driver.
Also, pressing the RetroArch menu switching key does not switch to the RetroArch menu.
There is no problem with DirectSound and Xaudio.

**Comment by Ghabry** [comment]
can't reproduce, works for me.

Also I don't understand how such bugs can be a core issue. The cores just call into the audio functions RetroArch provides.

**Comment by Ghabry** [comment]
"Also, pressing the RetroArch menu switching key does not switch to the RetroArch menu." what is this key? Do you mean F1? Have no problems with that.

**Comment by Ghabry** [comment]
@nanitaro 

I can reproduce this with the newest RetroArch version but imo this is a RetroArch and not a Core bug because I just use the interface exported via libretro.

Please file this bug again at https://github.com/libretro/RetroArch

**Comment by nanitaro** [comment]
@Ghabry 
Thank you for your assistance.
