### ISSUE TITLE
Compilation problem for Vita Core

### ISSUE THREAD

**Issue by FmT0** [libretro/easyrpg-libretro#42]
Compilation of easyrpg for PS Vita cannot complete. Here is the error I get for some months now : 

[ 15%] Building CXX object CMakeFiles/EasyRPG_Player.dir/src/decoder_libsndfile.cpp.obj
[ 15%] Building CXX object CMakeFiles/EasyRPG_Player.dir/src/decoder_mpg123.cpp.obj
/Volumes/Meisei/Retrogame/RetroCustomBuild/libretro-super/libretro-easyrpg/src/decoder_libsndfile.cpp: In function 'sf_count_t sf_vio_get_filelen_impl(void*)':
/Volumes/Meisei/Retrogame/RetroCustomBuild/libretro-super/libretro-easyrpg/src/decoder_libsndfile.cpp:30:9: error: 'fileno' was not declared in this scope
  int fd=fileno(f); //Posix complient - should work on windows as well
         ^~~~~~
/Volumes/Meisei/Retrogame/RetroCustomBuild/libretro-super/libretro-easyrpg/src/decoder_libsndfile.cpp:30:9: note: suggested alternative: 'fopen'
  int fd=fileno(f); //Posix complient - should work on windows as well
         ^~~~~~
         fopen
make[3]: *** [CMakeFiles/EasyRPG_Player.dir/src/decoder_libsndfile.cpp.obj] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/EasyRPG_Player.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [easyrpg_libretro_vita.a] Error 2

Do you have any idea what am I doing wrong ? I tried both on macosx and linux debian-stretch and still the same.

**Comment by Ghabry** [comment]
The internet suggests adding "#define _POSIX_C_SOURCE 200809L" before the first include in decoder_libsndfile.cpp (which means putting it on line 17)

I can already tell you that, even when it compiles, it will just boot into a black screen and nobody of us has a Vita to debug this.

We also offer a standalone EasyRPG Player Vita VPK: https://easyrpg.org/player/downloads/ (Tab "Other")

**Comment by FmT0** [comment]
Compilation is not going any further with "#define _POSIX_C_SOURCE 200809L"
Tried both macos and debian. Done some search to get a better define to get a successfull build but it's always the same "fileno error".
Anyway standalone seems for me a better option. You can close this issue unless you want me to try further.
