### ISSUE TITLE
Does not compile on iOS arm64 anymore

### ISSUE THREAD

**Issue by jet082** [libretro/easyrpg-libretro#44]
I have used brew to install cmake and pkg-config. That got the install as far as this, when it seemed to run into a 32/64-bit version conflict with some icu libraries.

This did use to compile on ios arm64, but broke some time ago.

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive member: ../lib/libicuuc.a(ucnv2022.ao) cputype (16777223) does not match previous archive members cputype (16777228) (all members must match)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive member: ../lib/libicuuc.a(ucnv_set.ao) cputype (16777223) does not match previous archive members cputype (16777228) (all members must match)
ranlib ../lib/libicuuc.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive member: ../lib/libicuuc.a(ucnv2022.ao) cputype (16777223) does not match previous archive members cputype (16777228) (all members must match)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive member: ../lib/libicuuc.a(ucnv_set.ao) cputype (16777223) does not match previous archive members cputype (16777228) (all members must match)

```

**Comment by Ghabry** [comment]
Which version of OSX are you using?

**Comment by Ghabry** [comment]
Works for me, I use OSX 10.13.6 and ``make -f Makefile.libretro platform=ios-arm64``

**Comment by jet082** [comment]
I am currently using 10.14.6. I am compiling via libretro-super. Using ``libretro-build-ios-arm64.sh easyrpg`` on the latest xcode.

**Comment by jet082** [comment]
I just ran ``make -f Makefile.libretro platform=ios-arm64`` in ``libretro-super/libretro-easyrpg/builds/libretro`` and the same error popped up.

**Comment by Ghabry** [comment]
guess I have to retest this when I find time to update my OSX install.

**Comment by jet082** [comment]
I was able to get it to build by commenting out the following line:

``install_lib_icu_native``

in ``builds/libretro/deps/libretro/2_build_cross_toolchain.sh``

**Comment by Ghabry** [comment]
thats strange because ICU native is needed to generate the datafile for the cross build. Did you start from a fresh git repo checkout before building?

**Comment by jet082** [comment]
So, just to verify, I deleted the directory and fetched it again. Editing that one line was insufficient to build it after all.

So I ran a few tests starting from scratch each time trying to recreate my success and I got one to work without commenting any files out. It turns out all you need to do is run ``git submodule update --init --recursive`` from the root directory.

**Comment by Ghabry** [comment]
That you need a submodule is documented in the README.md.
Okay, closing this then.

**Comment by jet082** [comment]
Once you have built this once, it will not build again without doing the following (or deleting and re-fetching):

```
git clean -xfd
git submodule foreach --recursive git clean -xfd
git reset --hard
git submodule foreach --recursive git reset --hard
git submodule update --init --recursive
```
