### ISSUE TITLE
RetroPad Settings don't Save/Load

### ISSUE THREAD

**Issue by snaphat** [libretro/easyrpg-libretro#51]
#### Player platform:
Platform: Windows 10

Issue: 

The retropad settings for the easyrpg core don't save upon exit (even if manually saved). Additionally, if modified by hand, they are not loaded on start and still report "None" in the Retroarch option menu.
The Debug mode and Input options work correctly so they are not shown below.

The core/game option file after saving settings:
```
RetroPad L = "None"
RetroPad L2 = "None"
RetroPad L3 = "None"
RetroPad R = "None"
RetroPad R2 = "None"
RetroPad R3 = "None"
RetroPad X = "None"
```

Modified options file which isn't loaded:
```
RetroPad L = "9"
RetroPad L2 = "None"
RetroPad L3 = "None"
RetroPad R = "5"
RetroPad R2 = "None"
RetroPad R3 = "None"
RetroPad X = "None"
```

**Comment by Kupo91** [comment]
I remember that I had this issue too.
I copied a remap file from gambatte and renamed it to "EasyRPG.rmp"
The content of my file looks like this:

```
input_libretro_device_p1 = "1"
input_libretro_device_p2 = "1"
input_libretro_device_p3 = "1"
input_libretro_device_p4 = "1"
input_libretro_device_p5 = "1"
input_player1_analog_dpad_mode = "0"
input_player1_btn_a = "0"
input_player1_btn_b = "8"
input_player1_btn_y = "-1"
input_player2_analog_dpad_mode = "0"
input_player3_analog_dpad_mode = "0"
input_player4_analog_dpad_mode = "0"
input_player5_analog_dpad_mode = "0"
```

But I also remember that I had issues again when I got a new gamepad. Even after adjusting the button names. However in the end I was able to fix it somehow. Sorry, that I cant help more, I just remember that it was very confusing for me too

**Comment by Ghabry** [comment]
This is now fixed upstream. I will apply the patch here too.
