### ISSUE TITLE
Content always identified as RPG_RT: no way to record playtime logs or customized options for each game

### ISSUE THREAD

**Issue by Ryunam** [libretro/easyrpg-libretro#52]
When using the libretro EasyRPG core (latest version as of the time of this issue, downloaded from the RA online updater) any content you load is identified internally as **RPG_RT**. 

This however makes it impossible to record a runtime log for each game, save customized core options, as well as overrides or input remaps that are specific to one game.

Perhaps it would be helpful to have the libretro core detect the `GameTitle` flag inside the RPG_RT.ini file and pass it on to RetroArch as the name of the content that is being played, so that the frontend can properly associate the game you are playing to its corresponding playtime log, override, remap or core option file.

**Comment by Ghabry** [comment]
This is a legitimate request.
Unfortunately I have no idea how to report a "game name" to solve this issue through the libretro API.

Could you help me here by researching this? (linking this issue e.g. in the libretro discord and forum and asking for help and then telling me the answer)
Then I will quickly implement this for you :). thanks! @Ryunam

**Comment by Ryunam** [comment]
Thank you for your quick response @Ghabry, much appreciated! I will definitely bring this up shortly in the libretro Discord server.

I was thinking that perhaps one way to work around this issue could be to have the libretro core accept .zip files as compatible filetypes for loading content. Then, the core would report the name of the .zip file itself to the frontend as the actual content title... But I'm not sure if that can actually work and/or how actually feasible it is to implement .zip file support.

**Comment by Ghabry** [comment]
We actually work upstream on zip support, then libretro will also get it. (we can also hook in libretro vfs but afaik the libretro vfs doesn't really support anything interesting).

**Comment by Ryunam** [comment]
I see, hopefully zip support can also solve this inconvenience with the libretro version. I've tried sharing your message on the libretro Discord, but so far I have not collected useful information for this purpose. I will try again for sure.

In the meantime, if there's anything I can test with regards to the upstream work that you are carrying out that may also yield a benefit for this issue, I will be glad to do that.

**Comment by Ghabry** [comment]
Thanks for the offer. I will ping you when I have something usable. Will take another mouth or two

**Comment by Ryunam** [comment]
Hi, sorry to bring this up again! I just wanted to see if there were any updates or new developments with regards to this little nuisance here.

Unfortunately as far as I can see this is still a problem with the libretro core, so it's still not possible to record per-game playtime logs or overrides.

**Comment by Ghabry** [comment]
The next release (comes Nov or Dec) will support games in zip archives. Then the name will be based on the name of the zip file.

What should already work in the current release is: Create a file called "GAME_NAME.easyrpg" in the game directory. This dummy file can be selected and launched.

**Comment by Ryunam** [comment]
Thank you! After updating both the core and the corresponding core info file from the buildbot, I confirm that using the GAME_NAME.easyrpg file in the game directory works perfectly for this purpose. 

I am going to close this issue since there is now a suitable solution that is immediately available for everyone, but I will be looking forward to the zip archive load functionality as well.
