### ISSUE TITLE
Graphical issues and broken gameplay mechanics in some games (Grimm's Hollow).

### ISSUE THREAD

**Issue by MikhailovDenegir** [libretro/easyrpg-libretro#53]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
Name of the game: Grimm's Hollow

#### Player platform:
Android, EMUElec (Linux)

#### Attach files (as a .zip archive or link them)
`easyrpg_log.txt` log file attached
[easyrpg_log.txt](https://github.com/libretro/easyrpg-libretro/files/6489301/easyrpg_log.txt)

#### Describe the issue in detail and how to reproduce it:
Grimm's Hollow has some graphical performance issues when running on most versions of RetroArch tested. It also has some broken gameplay mechanics. 

How to reproduce: Launch the game. Graphical issues are immediately apparent in game icons. Go into battle, and attempt to "swing." Completion of a swing attack is supposed to give "special points." It does not in this current build of the core. However, if you fill your "special points" with "Milk", the glitch goes away and the game functions normally for the duration of that battle. 

I have gotten the same issue on the Android version of RetroArch as well as the Linux version implemented for EmulationStation  via EmuELEC on the Anbernic RG351P.

**Comment by Ghabry** [comment]
Hello. Thanks for your report.

Please retest with a "continuous build" from our website. https://easyrpg.org/player/downloads/#release-linux

There are no cores available for it.

We are pretty sure that everything you reported is already fixed there.

The next stable release of player is scheduled for July. Then there will be also a new core release.

**Comment by MikhailovDenegir** [comment]
Thanks for the quick reply. 

I tried a couple of tests with the continuous builds on the website you referenced. On Vita, I was unable to check for fixes because the EasyRPG Maker app would crash upon loading Grimm's Hollow. I did test the stable build just to make sure it wasn't my Vita and the game did load, albeit with the graphical and gameplay issues mentioned in my original post. 

I was able to test on Android using the Retroid Pocket 2. The issues mentioned in my ticket were resolved, but there were a few odd graphical quirks. The "swing" meter would randomly appear in battle and there was a random sword in the air. Otherwise the graphical errors were fixed and I was able to see the "special points" meter go up as programmed. I was unable to test the libretro core because as you mentioned in your reply, there was no core under continuous build. 

Hope this helps. Thanks for your hard work. Looking forward to the new core release in July.

**Comment by Ghabry** [comment]
That one with the random sword sounds indeed like a (new) bug. That sword is part of Item animations (CBA) we did not implement before. This feature is kinda broken in the original engine (has tons of strange edge-cases) and is possible that we missed one here.
Does this random sword appear in all battles?

**Comment by Ghabry** [comment]
Reported this upstream as the bugs are not-core-related https://github.com/EasyRPG/Player/issues/2534

**Comment by MikhailovDenegir** [comment]
The random sword does indeed happen in all battles. Seems to pop up out of thin air whenever I “swing” in Grimm’s Hollow.

**Comment by Ghabry** [comment]
@MikhailovDenegir  I'm pretty sure the one with the Sword is a game bug. Try the following:

On Windows install the RTP 2003 (https://www.rpgmakerweb.com/run-time-package -> RPG Maker 2003).

Then run Grimm's Hollow and load Save01, savegame:
[GrimmsHollowSave.zip](https://github.com/libretro/easyrpg-libretro/files/6490217/GrimmsHollowSave.zip)
 (put it the LSD file in the same directory as the game):

Load the save. The tutorial will start and it should display the sword animation.

**Comment by MikhailovDenegir** [comment]
Confirmed. The phantom sword animation is there on Windows after following the directions in your last post.

**Comment by Ghabry** [comment]
Thanks. Will try to contact the author to get this fixed. Is nothing we can resolve on our end (at least not yet, for problematic games we plan a "game database" later so enable/disable certain patches. Similiar how emulators do it)

**Comment by MikhailovDenegir** [comment]
Ok sounds good. Thanks for everything!

**Comment by Ghabry** [comment]
@MikhailovDenegir 
Version 1.2 on itch.io fixes the bug with the random sword.

**Comment by MikhailovDenegir** [comment]
Thanks. Sorry the last couple of days have been busy. I will try loading it tonight to confirm.

**Comment by Ghabry** [comment]
The incorrect swing meter has now a patch submitted upstream. Closing this here.
