### ISSUE TITLE
Yume Nikki goes black when sitting at the desk to save

### ISSUE THREAD

**Issue by teconmoon** [libretro/easyrpg-libretro#55]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Describe the issue in detail and how to reproduce it:
When playing Yume Nikki using the RetroArch Core version of EasyRPG Player, sitting at the desk to save results in the screen going black instead of being illuminated by the desk lamp. The game is still controllable, and you can still proceed to the save menu and/or get out of the chair to continue playing.

This issue does not occur with the standalone EasyRPG Player "Sword" or the latest continuous build. I like the flexibility of being able to remap controls using the RetroArch core.

Steps to reproduce:

1. Launch the game
2. Start a new file
3. Sit at the desk

Logs here: https://pastebin.com/mefDDuEe

Screenshot of what the effect looks like using the standalone player attached. I'd paste a screenshot of what it actually is in the core, but it'd just be a black screenshot.
![Screenshot 2023-02-10 112516](https://user-images.githubusercontent.com/46909426/218185964-f3a98ca0-cb4a-449f-b358-fddb3dedaeaa.png)

**Comment by Ghabry** [comment]
This will be fixed in 0.8. Expect it in around a week on the core downloader.

If you cannot wait: you can get continuous builds of the core from our download page
