### ISSUE TITLE
Audio entry not correctly stopped when exiting a game when a midi is playing causing a crash

### ISSUE THREAD

**Issue by Mimigris** [libretro/easyrpg-libretro#59]
#### Name of the game:
[Shoukan Gaki 2nd](https://goburinbro.itch.io/mienu-monogatari-shoukan-gaki-2nd-unseen).

#### Player platform:
Windows, version 0.8.0 of the EasyRPG Player core while playing on RetroArch.

#### Describe the issue in detail and how to reproduce it:
When exiting the Player in RetroArch without asking RetroArch to entirely close, it is possible that the music previously playing will continue to play after exiting the Player. It seems to be music specific (likely with specific midi I guess though it may be more than that). This can be easily replicated in Shoukan Gaki 2nd when exiting from the title screen (the music in question is Vehicle3 from the RTP of RPG Maker 2000 and it is a midi file).

Here's a video showing the issue (note that the music was not edited): https://youtu.be/5NKyZoA78Z0

**Comment by Mimigris** [comment]
Forgot to check more about this part of the issue, but exiting a game while a midi music is playing and trying to launch another game (or the same) will crash the app. It seems that the fact that the entry is not entirely cleared/try to be replayed cause a fatal issue to the player.

**Comment by Ghabry** [comment]
closing this as moved to the upstream tracker
